# -*- coding: utf-8 -*-
"""Airline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12f3NrInNgzz0Bgn26huaPWg_BLg4mAYA

DAY 13
"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

"""### Route Frequency Density Word Cloud

Using the previously prepared `text_content` that combines destination cities and airlines, I will now generate and display the word cloud to visualize the route frequency density.
"""

# Generate the word cloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text_content)

# Display the generated image:
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Route Frequency Density Word Cloud (Cities and Airlines)')
plt.show()
