# -*- coding: utf-8 -*-
"""superstore_day 1-day 11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Xy_-4cisSL3fkKLMuDTirPGjZCNsJQo

#DAY1
"""

print("python for Data Analysis with AI assistance")

name = input()
print(name)

# Import required libraries
import numpy as np
import pandas as pd
print ("Numpy imported successfully")
print ("pandas imported successfully")

# loading dataset
df = pd.read_csv("/content/samplesuperstore.csv")
print("Dataset loaded successfully1!")

#SUPERSTORE DATASET

import kagglehub

#Download latest version
path = kagglehub.dataset_download("himanshuuike/superstore-sales-dataset")

print("Path to dataset files:",path)
import os

print(os.listdir(path))

import pandas as pd

df=pd.read_csv(os.path.join(path,"samplesuperstore.csv"))

print("Dataset loaded successfully")

# import libraries
import pandas as pd

print("Pandas imported successfully!")
df=pd.read_csv("/content/samplesuperstore.csv")
print("Dataset loaded successfully")

"""Task1--Inspect the Superstore Dataset

Display:
1.First 10 rows
2.Last 10 rows
3.Number of rows and columns
4.Column names
"""

display(df.head(10))
display(df.tail(10))

print("Shape:",df.shape)

print("columns:")
print(df.columns.tolist())

"""## Task 2--Select important columns

Display only:

Customer name
Catogory
Sales
Profit

Show the first 10 records."""

df[
    ["Customer Name","Category","Sales","Profit"]
].head(10)

""" Task 3 - High Sales Records

Find all records where Sales is greater than 500.

Display the first 10 results. """

high_sales = df[df["Sales"] > 500]

print("Number:",len(high_sales))

display(high_sales.head(10))

from google.colab import drive
drive.mount('/content/drive')

"""DAY 3

Task 4--Filter by category

Display records belonging to the Technology category

Show:
Customer Name
Product name
Sales
Profit

Display the first 10 records.

## Task 5--High Sales and High Profit

Find records where:
Sales>500
Profit>100
Both conditions must be satisfied.

Task 6--High Sales OR High Profit

Find records where:
Sales>1000

OR

Profit>500

Task 7--Understand Catogories

Find:

1.Different categories
2.Number of categories
3.Number of records in each category

Task 8--Analyse Regions

Find:
1.All unique regions
2.Number of regions
3.Number of records in each region

Task 9--Analyse Sales

Calculate:

Total Sales
Average Sales
Medium Sales
Minimum Sales
Maximum Sales

Task 10--Analyse Profit

Calculate:

Total Profit
Average Profit
Minimum Profit
Maximum Profit

Then identify whether the overall total profit is positive or negative

DAY 5
"""

#SUPERSTORE DATASET

import kagglehub

#Download latest version
path = kagglehub.dataset_download("himanshuuike/superstore-sales-dataset")

print("Path to dataset files:",path)
import os

print(os.listdir(path))

import pandas as pd

df_superstore.read_csv(os.path.join(path,"samplesuperstore.csv"))

print("Dataset loaded successfully")#

task1_superstore = df.groupby('Region')['Sales'].sum().reset_index()
print(task1_superstore)

task2_superstore = df.groupby(['Category', 'Sub-Category'])[['Sales', 'Profit']].sum().reset_index()
print(task2_superstore.head(5))

task3_superstore = df.groupby('Category').agg(
    Avg_sales=('Sales','mean'),
    Min_profit=('Profit','min'),
    Max_profit=('Profit','max')
).reset_index()
print(task3_superstore)

task4_superstore = (df.groupby('Sub-Category')['Profit']
                    .sum()
                    .reset_index()
                    .sort_values(by='Profit',ascending=False)
                    .head(5))
print(task4_superstore)

task5_superstore = df.groupby('Segment').agg(
    Total_Order=('Row ID','count'),
    Avg_Discount=('Discount','mean'),
    Total_Profit=('Profit','sum')
).reset_index()
print(task5_superstore)

task6_superstore = df.groupby('City').filter(lambda x: x['Sales'].sum()>50000)
print("Qualified cities:",task6_superstore['City'].unique())
print("Retained Rows Ratio:",f"{len(task6_superstore)} / {len(df)}")

"""DAY 7

task1:convert Order Date to datetime and extract year,month,and day name
"""

# Convert 'Order Date' to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'])

# Extract Year, Month, and Day Name
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month
df['Day_Name'] = df['Order Date'].dt.day_name()

print("Date columns processed successfully.")
display(df[['Order Date', 'Year', 'Month', 'Day_Name']].head())

"""task2: clean and standardize Customer Name"""

df['Customer Name'] = df['Customer Name'].str.strip().str.upper()

print("'Customer Name' column processed (stripped whitespaces and converted to uppercase).")
print(df['Customer Name'].head())

"""task3: calculate percentage contribution of each order to category total sales"""

# Calculate total sales for each category
df['Category Total Sales'] = df.groupby('Category')['Sales'].transform('sum')

# Calculate each order's percentage contribution to its category's total sales
df['Percentage Contribution'] = (df['Sales'] / df['Category Total Sales']) * 100

print("Percentage contribution of each order to category total sales calculated.")
display(df[['Category', 'Sales', 'Category Total Sales', 'Percentage Contribution']].head())

"""task4:construct a pivot table of total sales by region and category"""

pivot_table_sales = pd.pivot_table(df, values='Sales', index='Region', columns='Category', aggfunc='sum')
display(pivot_table_sales)

"""task5: unpivot category sales data using melt()"""

unpivoted_sales = pivot_table_sales.reset_index().melt(id_vars=['Region'], var_name='Category', value_name='Sales')
display(unpivoted_sales.head())

"""task6:merge regional target sales dataframe with superstore data"""

regional_target_sales = pd.DataFrame({
    'Region': ['Central', 'East', 'South', 'West'],
    'Target Sales': [200000, 250000, 150000, 300000]
})

print("Regional Target Sales DataFrame created:")
display(regional_target_sales)

df_merged = pd.merge(df, regional_target_sales, on='Region', how='inner')

print("DataFrames merged successfully based on 'Region':")
display(df_merged.head())

"""day 9 & 10

day 11

task1:Matplotlib 3D scatter plot(sales vs profit vs quantity)
"""

import pandas as pd
import kagglehub
import os

# Load the dataset to define 'df'
path = kagglehub.dataset_download("himanshuuike/superstore-sales-dataset")
df = pd.read_csv(os.path.join(path, "samplesuperstore.csv"))

# Define 'regional_target_sales' DataFrame
regional_target_sales = pd.DataFrame({
    'Region': ['Central', 'East', 'South', 'West'],
    'Target Sales': [200000, 250000, 150000, 300000]
})

# Merge df and regional_target_sales to create df_merged
df_merged = pd.merge(df, regional_target_sales, on='Region', how='inner')

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Create a 3D scatter plot
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# Scatter plot with Sales (x), Profit (y), Quantity (z), and color by Profit
scatter = ax.scatter(
    df_merged['Sales'],
    df_merged['Profit'],
    df_merged['Quantity'],
    c=df_merged['Profit'], # Color by profit
    cmap='viridis', # Colormap for profit
    s=50, # Marker size
    alpha=0.7 # Transparency
)

# Set labels for axes
ax.set_xlabel('Sales')
ax.set_ylabel('Profit')
ax.set_zlabel('Quantity')
ax.set_title('3D Scatter Plot of Sales, Profit, and Quantity (Colored by Profit)')

# Add a color bar
cbar = fig.colorbar(scatter, shrink=0.5, aspect=10)
cbar.set_label('Profit Scale')

plt.show()

"""task2: Matplotlib 3D surface plot of synthetic sales-profit surface"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Get the range for Sales and Profit from df_merged
x_min, x_max = df_merged['Sales'].min(), df_merged['Sales'].max()
y_min, y_max = df_merged['Profit'].min(), df_merged['Profit'].max()

# Create a meshgrid for Sales (X) and Profit (Y)
X = np.linspace(x_min, x_max, 100)
Y = np.linspace(y_min, y_max, 100)
X, Y = np.meshgrid(X, Y)

# Define a hypothetical function for Quantity (Z) based on Sales and Profit
# This is a placeholder function to illustrate a smooth surface.
# In a real scenario, you might derive this from a regression model or domain knowledge.
Z = (X + Y) / 500 + np.sin(X / 100) + np.cos(Y / 100) # Example function

# Create the 3D surface plot
fig = plt.figure(figsize=(12, 10))
ax = fig.add_subplot(111, projection='3d')

# Plot the surface
surface = ax.plot_surface(X, Y, Z, cmap='viridis', edgecolor='none')

# Set labels and title
ax.set_xlabel('Sales')
ax.set_ylabel('Profit')
ax.set_zlabel('Quantity (Hypothetical)')
ax.set_title('3D Smooth Surface Plot of Sales, Profit, and Hypothetical Quantity')

# Add a color bar for the surface
fig.colorbar(surface, shrink=0.5, aspect=10, label='Quantity Scale')

plt.show()

"""task3:plotly interactive 3D scatter plot"""

import plotly.express as px

# Create an interactive 3D scatter plot
fig = px.scatter_3d(df_merged,
                    x='Sales',
                    y='Profit',
                    z='Quantity',
                    color='Category',
                    title='Interactive 3D Scatter Plot of Sales, Profit, and Quantity by Category')

# Display the plot
fig.show()

"""task4: hierarchical treemapvisualization"""

import plotly.express as px

# Create a Treemap plot
fig = px.treemap(df_merged,
                 path=['Region', 'Category', 'Sub-Category'],
                 values='Sales',
                 title='Sales Hierarchy by Region, Category, and Sub-Category')

# Display the plot
fig.show()

"""task5:intractive sunburst chart"""

import plotly.express as px

# Create a Sunburst chart
fig = px.sunburst(df_merged,
                  path=['Region', 'Category'],
                  values='Sales',
                  title='Sales Breakdown by Region and Category')

# Display the plot
fig.show()

"""task6: plotly interactive bubble chart"""

import plotly.express as px

# Create a 2D scatter bubble chart
fig = px.scatter(df_merged,
                 x='Sales',
                 y='Profit',
                 size='Quantity',
                 title='Sales vs. Profit (Bubble Size by Quantity)',
                 hover_name='Customer Name' # Optional: show customer name on hover
                )

# Display the plot
fig.show()

"""task7:interactive box plot with hover points"""

import plotly.express as px

# Create a Plotly box plot of Profit across Regions, showing all points
fig = px.box(df_merged,
             x='Region',
             y='Profit',
             points='all', # Show all data points
             title='Profit Distribution Across Regions with Individual Data Points')

# Display the plot
fig.show()

"""task8:plotly parallel coordinates plot"""

import plotly.express as px

# Create a Parallel Coordinates chart
fig = px.parallel_coordinates(df_merged,
                              dimensions=['Sales', 'Profit', 'Quantity', 'Discount'],
                              title='Parallel Coordinates Plot of Sales, Profit, Quantity, and Discount')

# Display the plot
fig.show()

"""task9: dual-axis interactive graph objects chart"""

import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Aggregate data by Category for Sales and Profit
df_agg_category = df_merged.groupby('Category')[['Sales', 'Profit']].sum().reset_index()

# Create subplots with a secondary y-axis
fig = make_subplots(specs=[[{"secondary_y": True}]])

# Add Sales as a bar chart on the primary y-axis
fig.add_trace(
    go.Bar(x=df_agg_category['Category'], y=df_agg_category['Sales'], name='Total Sales'),
    secondary_y=False,
)

# Add Profit as a line chart on the secondary y-axis
fig.add_trace(
    go.Scatter(x=df_agg_category['Category'], y=df_agg_category['Profit'], name='Total Profit', mode='lines+markers'),
    secondary_y=True,
)

# Add figure title and axis titles
fig.update_layout(
    title_text="Total Sales and Total Profit by Category (Dual Y-Axis)"
)
fig.update_xaxes(title_text="Category")
fig.update_yaxes(title_text="Total Sales", secondary_y=False)
fig.update_yaxes(title_text="Total Profit", secondary_y=True)

# Display the plot
fig.show()

"""task10: customized dark theme animated sider chart"""

import plotly.express as px

# Convert 'Discount' to string for animation_frame to treat it as discrete steps
df_merged['Discount_Str'] = df_merged['Discount'].astype(str)

# Create a scatter plot with animation_frame for Discount and dark theme
fig = px.scatter(df_merged,
                 x='Sales',
                 y='Profit',
                 size='Quantity',
                 color='Category',
                 animation_frame='Discount_Str',
                 animation_group='Customer Name',
                 hover_name='Customer Name',
                 title='Sales vs. Profit by Quantity with Discount Slider (Dark Theme)',
                 log_x=True, # Log scale for better distribution visualization
                 size_max=60,
                 range_x=[df_merged['Sales'].min(), df_merged['Sales'].max()],
                 range_y=[df_merged['Profit'].min(), df_merged['Profit'].max()],
                 template='plotly_dark')

# Adjust layout and animation speed
fig.layout.updatemenus[0].buttons[0].args[1]['frame']['duration'] = 500
fig.layout.updatemenus[0].buttons[0].args[1]['transition']['duration'] = 300

# Display the plot
fig.show()

"""DAY 13"""

!pip install squarify
!pip install ydata_profiling
!pip install wordcloud
!pip install dash

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import missingno as msno
import squarify
from wordcloud import WordCloud
from ydata_profiling import ProfileReport

import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import plotly.express as px
import plotly.graph_objects as go

import kagglehub
import os

# 1. Load / Prepare Superstore Dataset with artificial missing values for diagnostics
np.random.seed(42)
n = 200

df_superstore = pd.DataFrame({
    'Sales': np.random.uniform(50.0, 2000.0, n).round(2),
    'Profit': np.random.uniform(-200.0, 500.0, n).round(2),
    'Quantity': np.random.randint(1, 15, n),
    'Discount': np.random.choice([0.0, 0.1, 0.2, 0.3, 0.5], n),
    'Category': np.random.choice(['Furniture', 'Technology', 'Office Supplies'], n),
    'Sub-Category': np.random.choice(['Chairs', 'Phones', 'Paper', 'Binders', 'Storage', 'Tables'], n),
    'Region': np.random.choice(['East', 'West', 'South', 'Central'], n)
})

# Inject synthetic missing values into Superstore dataset for missingness tasks
df_superstore_missing = df_superstore.copy()
df_superstore_missing.loc[df_superstore_missing.sample(frac=0.15, random_state=1).index, 'Sales'] = np.nan
df_superstore_missing.loc[df_superstore_missing.sample(frac=0.20, random_state=2).index, 'Profit'] = np.nan
df_superstore_missing.loc[df_superstore_missing.sample(frac=0.10, random_state=3).index, 'Discount'] = np.nan

print("Superstore Dataset loaded successfully.")
print("Superstore missing values shape:", df_superstore_missing.shape)

"""task 1-5: diagnostics,profiling & specialized charts

Task 1: Missing Data Matrix Pattern using Missingno
"""

msno.matrix(df_superstore_missing, figsize=(10, 5), color=(0.2, 0.2, 0.4))
plt.title('Missing Data Matrix of Superstore Dataset')
plt.show()

"""Task 2: Nullity correlation heatmap using missingno"""

msno.heatmap(df_superstore_missing, figsize=(10, 5), cmap='viridis')
plt.title('Nullity Correlation Heatmap of Superstore Dataset')
plt.show()

"""task:3 : stat"""

# Calculate total sales for each Sub-Category
subcategory_sales = df_superstore.groupby('Sub-Category')['Sales'].sum().reset_index()

# Sort for better visualization (optional)
subcategory_sales = subcategory_sales.sort_values(by='Sales', ascending=False)

# Create the treemap
plt.figure(figsize=(12, 8))
squarify.plot(sizes=subcategory_sales['Sales'], label=subcategory_sales['Sub-Category'], alpha=0.8)
plt.title('Total Sales by Sub-Category (Treemap)')
plt.axis('off') # Hide axes
plt.show()

"""task 5: Automated EDA Report Generation using Ydata-Profiling"""

profile = ProfileReport(df_superstore, title='Superstore Dataset Profiling Report')
profile.to_file("superstore_profile_report.html")
print("Automated EDA report generated and saved as 'superstore_profile_report.html'")

